# Filename: ITK_LIBS_540.cmake

set(ITK_LIB_540_Release
optimized hdf5_hl_cpp-static.lib
optimized ITKBiasCorrection-5.4.lib
optimized ITKColormap-5.4.lib
optimized ITKCommon-5.4.lib
optimized ITKConvolution-5.4.lib
optimized itkCudaCommon-5.4.lib
optimized ITKDeformableMesh-5.4.lib
optimized ITKDenoising-5.4.lib
optimized ITKDICOMParser-5.4.lib
optimized ITKDiffusionTensorImage-5.4.lib
optimized itkdouble-conversion-5.4.lib
optimized ITKEXPAT-5.4.lib
optimized ITKFastMarching-5.4.lib
optimized ITKFFT-5.4.lib
optimized itkgdcmcharls-5.4.lib
optimized itkgdcmCommon-5.4.lib
optimized itkgdcmDICT-5.4.lib
optimized itkgdcmDSED-5.4.lib
optimized itkgdcmIOD-5.4.lib
optimized itkgdcmjpeg12-5.4.lib
optimized itkgdcmjpeg16-5.4.lib
optimized itkgdcmjpeg8-5.4.lib
optimized itkgdcmMEXD-5.4.lib
optimized itkgdcmMSFF-5.4.lib
optimized itkgdcmopenjp2-5.4.lib
optimized itkgdcmsocketxx-5.4.lib
optimized ITKgiftiio-5.4.lib
optimized itkhdf5-shared-5.4.lib
optimized itkhdf5-static-5.4.lib
optimized itkhdf5_cpp-shared-5.4.lib
optimized itkhdf5_cpp-static-5.4.lib
optimized itkhdf5_hl-shared-5.4.lib
optimized itkhdf5_hl-static-5.4.lib
optimized ITKImageFeature-5.4.lib
optimized ITKImageIntensity-5.4.lib
optimized ITKIOBioRad-5.4.lib
optimized ITKIOBMP-5.4.lib
optimized ITKIOBruker-5.4.lib
optimized ITKIOCSV-5.4.lib
optimized ITKIOGDCM-5.4.lib
optimized ITKIOGE-5.4.lib
optimized ITKIOGIPL-5.4.lib
optimized ITKIOHDF5-5.4.lib
optimized ITKIOImageBase-5.4.lib
optimized ITKIOIPL-5.4.lib
optimized ITKIOJPEG-5.4.lib
optimized ITKIOJPEG2000-5.4.lib
optimized ITKIOLSM-5.4.lib
optimized ITKIOMeshBase-5.4.lib
optimized ITKIOMeshBYU-5.4.lib
optimized ITKIOMeshFreeSurfer-5.4.lib
optimized ITKIOMeshGifti-5.4.lib
optimized ITKIOMeshOBJ-5.4.lib
optimized ITKIOMeshOFF-5.4.lib
optimized ITKIOMeshVTK-5.4.lib
optimized ITKIOMeta-5.4.lib
optimized ITKIOMINC-5.4.lib
optimized ITKIOMRC-5.4.lib
optimized ITKIONIFTI-5.4.lib
optimized ITKIONRRD-5.4.lib
optimized ITKIOPNG-5.4.lib
optimized ITKIOSiemens-5.4.lib
optimized ITKIOSpatialObjects-5.4.lib
optimized ITKIOStimulate-5.4.lib
optimized ITKIOTIFF-5.4.lib
optimized ITKIOTransformBase-5.4.lib
optimized ITKIOTransformHDF5-5.4.lib
optimized ITKIOTransformInsightLegacy-5.4.lib
optimized ITKIOTransformMatlab-5.4.lib
optimized ITKIOVTK-5.4.lib
optimized ITKIOXML-5.4.lib
optimized itkjpeg-5.4.lib
optimized ITKKLMRegionGrowing-5.4.lib
optimized ITKLabelMap-5.4.lib
optimized itklbfgs-5.4.lib
optimized itklpsolve55-5.4.lib
optimized ITKMarkovRandomFieldsClassifiers-5.4.lib
optimized ITKMathematicalMorphology-5.4.lib
optimized ITKMesh-5.4.lib
optimized ITKMetaIO-5.4.lib
optimized itkminc2-5.4.lib
optimized itkNetlibSlatec-5.4.lib
optimized ITKniftiio-5.4.lib
optimized ITKNrrdIO-5.4.lib
optimized itkopenjpeg-5.4.lib
optimized ITKOptimizers-5.4.lib
optimized ITKOptimizersv4-5.4.lib
optimized ITKPath-5.4.lib
optimized ITKPDEDeformableRegistration-5.4.lib
optimized itkpng-5.4.lib
optimized ITKPolynomials-5.4.lib
optimized ITKQuadEdgeMesh-5.4.lib
optimized ITKQuadEdgeMeshFiltering-5.4.lib
optimized ITKRegionGrowing-5.4.lib
optimized ITKRegistrationMethodsv4-5.4.lib
optimized itkRTK-5.4.lib
optimized ITKSmoothing-5.4.lib
optimized ITKSpatialObjects-5.4.lib
optimized ITKStatistics-5.4.lib
optimized itksys-5.4.lib
optimized ITKTestKernel-5.4.lib
optimized itktestlib-5.4.lib
optimized itktiff-5.4.lib
optimized ITKTransform-5.4.lib
optimized ITKTransformFactory-5.4.lib
optimized itkv3p_netlib-5.4.lib
optimized itkvcl-5.4.lib
optimized ITKVideoBridgeOpenCV-5.4.lib
optimized ITKVideoCore-5.4.lib
optimized ITKVideoIO-5.4.lib
optimized itkvnl-5.4.lib
optimized ITKVNLInstantiation-5.4.lib
optimized itkvnl_algo-5.4.lib
optimized ITKVTK-5.4.lib
optimized ITKVtkGlue-5.4.lib
optimized ITKWatersheds-5.4.lib
optimized itkzlib-5.4.lib
optimized ITKznz-5.4.lib
)
set(ITK_LIB_540_Debug
debug hdf5_hl_cpp-shared.lib
debug hdf5_hl_cpp-sharedd.lib
debug hdf5_hl_cpp-staticd.lib
debug ITKBiasCorrection-5.4d.lib
debug ITKColormap-5.4d.lib
debug ITKCommon-5.4d.lib
debug ITKConvolution-5.4d.lib
debug itkCudaCommon-5.4d.lib
debug ITKDeformableMesh-5.4d.lib
debug ITKDenoising-5.4d.lib
debug ITKDICOMParser-5.4d.lib
debug ITKDiffusionTensorImage-5.4d.lib
debug itkdouble-conversion-5.4d.lib
debug ITKEXPAT-5.4d.lib
debug ITKFastMarching-5.4d.lib
debug ITKFFT-5.4d.lib
debug itkgdcmcharls-5.4d.lib
debug itkgdcmCommon-5.4d.lib
debug itkgdcmDICT-5.4d.lib
debug itkgdcmDSED-5.4d.lib
debug itkgdcmIOD-5.4d.lib
debug itkgdcmjpeg12-5.4d.lib
debug itkgdcmjpeg16-5.4d.lib
debug itkgdcmjpeg8-5.4d.lib
debug itkgdcmMEXD-5.4d.lib
debug itkgdcmMSFF-5.4d.lib
debug itkgdcmopenjp2-5.4d.lib
debug itkgdcmsocketxx-5.4d.lib
debug ITKgiftiio-5.4d.lib
debug itkhdf5-shared-5.4d.lib
debug itkhdf5-static-5.4d.lib
debug itkhdf5_cpp-shared-5.4d.lib
debug itkhdf5_cpp-static-5.4d.lib
debug itkhdf5_hl-shared-5.4d.lib
debug itkhdf5_hl-static-5.4d.lib
debug ITKImageFeature-5.4d.lib
debug ITKImageIntensity-5.4d.lib
debug ITKIOBioRad-5.4d.lib
debug ITKIOBMP-5.4d.lib
debug ITKIOBruker-5.4d.lib
debug ITKIOCSV-5.4d.lib
debug ITKIOGDCM-5.4d.lib
debug ITKIOGE-5.4d.lib
debug ITKIOGIPL-5.4d.lib
debug ITKIOHDF5-5.4d.lib
debug ITKIOImageBase-5.4d.lib
debug ITKIOIPL-5.4d.lib
debug ITKIOJPEG-5.4d.lib
debug ITKIOJPEG2000-5.4d.lib
debug ITKIOLSM-5.4d.lib
debug ITKIOMeshBase-5.4d.lib
debug ITKIOMeshBYU-5.4d.lib
debug ITKIOMeshFreeSurfer-5.4d.lib
debug ITKIOMeshGifti-5.4d.lib
debug ITKIOMeshOBJ-5.4d.lib
debug ITKIOMeshOFF-5.4d.lib
debug ITKIOMeshVTK-5.4d.lib
debug ITKIOMeta-5.4d.lib
debug ITKIOMINC-5.4d.lib
debug ITKIOMRC-5.4d.lib
debug ITKIONIFTI-5.4d.lib
debug ITKIONRRD-5.4d.lib
debug ITKIOPNG-5.4d.lib
debug ITKIOSiemens-5.4d.lib
debug ITKIOSpatialObjects-5.4d.lib
debug ITKIOStimulate-5.4d.lib
debug ITKIOTIFF-5.4d.lib
debug ITKIOTransformBase-5.4d.lib
debug ITKIOTransformHDF5-5.4d.lib
debug ITKIOTransformInsightLegacy-5.4d.lib
debug ITKIOTransformMatlab-5.4d.lib
debug ITKIOVTK-5.4d.lib
debug ITKIOXML-5.4d.lib
debug itkjpeg-5.4d.lib
debug ITKKLMRegionGrowing-5.4d.lib
debug ITKLabelMap-5.4d.lib
debug itklbfgs-5.4d.lib
debug itklpsolve55-5.4d.lib
debug ITKMarkovRandomFieldsClassifiers-5.4d.lib
debug ITKMathematicalMorphology-5.4d.lib
debug ITKMesh-5.4d.lib
debug ITKMetaIO-5.4d.lib
debug itkminc2-5.4d.lib
debug itkNetlibSlatec-5.4d.lib
debug ITKniftiio-5.4d.lib
debug ITKNrrdIO-5.4d.lib
debug itkopenjpeg-5.4d.lib
debug ITKOptimizers-5.4d.lib
debug ITKOptimizersv4-5.4d.lib
debug ITKPath-5.4d.lib
debug ITKPDEDeformableRegistration-5.4d.lib
debug itkpng-5.4d.lib
debug ITKPolynomials-5.4d.lib
debug ITKQuadEdgeMesh-5.4d.lib
debug ITKQuadEdgeMeshFiltering-5.4d.lib
debug ITKRegionGrowing-5.4d.lib
debug ITKRegistrationMethodsv4-5.4d.lib
debug itkRTK-5.4d.lib
debug ITKSmoothing-5.4d.lib
debug ITKSpatialObjects-5.4d.lib
debug ITKStatistics-5.4d.lib
debug itksys-5.4d.lib
debug ITKTestKernel-5.4d.lib
debug itktestlib-5.4d.lib
debug itktiff-5.4d.lib
debug ITKTransform-5.4d.lib
debug ITKTransformFactory-5.4d.lib
debug itkv3p_netlib-5.4d.lib
debug itkvcl-5.4d.lib
debug ITKVideoBridgeOpenCV-5.4d.lib
debug ITKVideoCore-5.4d.lib
debug ITKVideoIO-5.4d.lib
debug itkvnl-5.4d.lib
debug ITKVNLInstantiation-5.4d.lib
debug itkvnl_algo-5.4d.lib
debug ITKVTK-5.4d.lib
debug ITKVtkGlue-5.4d.lib
debug ITKWatersheds-5.4d.lib
debug itkzlib-5.4d.lib
debug ITKznz-5.4d.lib
)