# Filename: VTK_LIBS.cmake

set(VTK_LIB_Release  
optimized vtkChartsCore-9.0.lib
optimized vtkCommonColor-9.0.lib
optimized vtkCommonComputationalGeometry-9.0.lib
optimized vtkCommonCore-9.0.lib
optimized vtkCommonDataModel-9.0.lib
optimized vtkCommonExecutionModel-9.0.lib
optimized vtkCommonMath-9.0.lib
optimized vtkCommonMisc-9.0.lib
optimized vtkCommonSystem-9.0.lib
optimized vtkCommonTransforms-9.0.lib
optimized vtkDICOMParser-9.0.lib
optimized vtkDomainsChemistry-9.0.lib
optimized vtkdoubleconversion-9.0.lib
optimized vtkexodusII-9.0.lib
optimized vtkexpat-9.0.lib
optimized vtkFiltersAMR-9.0.lib
optimized vtkFiltersCore-9.0.lib
optimized vtkFiltersExtraction-9.0.lib
optimized vtkFiltersFlowPaths-9.0.lib
optimized vtkFiltersGeneral-9.0.lib
optimized vtkFiltersGeneric-9.0.lib
optimized vtkFiltersGeometry-9.0.lib
optimized vtkFiltersHybrid-9.0.lib
optimized vtkFiltersHyperTree-9.0.lib
optimized vtkFiltersImaging-9.0.lib
optimized vtkFiltersModeling-9.0.lib
optimized vtkFiltersParallel-9.0.lib
optimized vtkFiltersParallelImaging-9.0.lib
optimized vtkFiltersPoints-9.0.lib
optimized vtkFiltersProgrammable-9.0.lib
optimized vtkFiltersSelection-9.0.lib
optimized vtkFiltersSMP-9.0.lib
optimized vtkFiltersSources-9.0.lib
optimized vtkFiltersStatistics-9.0.lib
optimized vtkFiltersTexture-9.0.lib
optimized vtkFiltersTopology-9.0.lib
optimized vtkFiltersVerdict-9.0.lib
optimized vtkfreetype-9.0.lib
optimized vtkGeovisCore-9.0.lib
optimized vtkgl2ps-9.0.lib
optimized vtkglew-9.0.lib
optimized vtkGUISupportQt-9.0.lib
optimized vtkGUISupportQtSQL-9.0.lib
optimized vtkhdf5-9.0.lib
optimized vtkhdf5_hl-9.0.lib
optimized vtkImagingColor-9.0.lib
optimized vtkImagingCore-9.0.lib
optimized vtkImagingFourier-9.0.lib
optimized vtkImagingGeneral-9.0.lib
optimized vtkImagingHybrid-9.0.lib
optimized vtkImagingMath-9.0.lib
optimized vtkImagingMorphological-9.0.lib
optimized vtkImagingSources-9.0.lib
optimized vtkImagingStatistics-9.0.lib
optimized vtkImagingStencil-9.0.lib
optimized vtkInfovisCore-9.0.lib
optimized vtkInfovisLayout-9.0.lib
optimized vtkInteractionImage-9.0.lib
optimized vtkInteractionStyle-9.0.lib
optimized vtkInteractionWidgets-9.0.lib
optimized vtkIOAMR-9.0.lib
optimized vtkIOAsynchronous-9.0.lib
optimized vtkIOCityGML-9.0.lib
optimized vtkIOCore-9.0.lib
optimized vtkIOEnSight-9.0.lib
optimized vtkIOExodus-9.0.lib
optimized vtkIOExport-9.0.lib
optimized vtkIOExportGL2PS-9.0.lib
optimized vtkIOExportPDF-9.0.lib
optimized vtkIOGeometry-9.0.lib
optimized vtkIOImage-9.0.lib
optimized vtkIOImport-9.0.lib
optimized vtkIOInfovis-9.0.lib
optimized vtkIOLegacy-9.0.lib
optimized vtkIOLSDyna-9.0.lib
optimized vtkIOMINC-9.0.lib
optimized vtkIOMotionFX-9.0.lib
optimized vtkIOMovie-9.0.lib
optimized vtkIONetCDF-9.0.lib
optimized vtkIOOggTheora-9.0.lib
optimized vtkIOParallel-9.0.lib
optimized vtkIOParallelXML-9.0.lib
optimized vtkIOPLY-9.0.lib
optimized vtkIOSegY-9.0.lib
optimized vtkIOSQL-9.0.lib
optimized vtkIOTecplotTable-9.0.lib
optimized vtkIOVeraOut-9.0.lib
optimized vtkIOVideo-9.0.lib
optimized vtkIOXML-9.0.lib
optimized vtkIOXMLParser-9.0.lib
optimized vtkjpeg-9.0.lib
optimized vtkjsoncpp-9.0.lib
optimized vtklibharu-9.0.lib
optimized vtklibproj-9.0.lib
optimized vtklibxml2-9.0.lib
optimized vtkloguru-9.0.lib
optimized vtklz4-9.0.lib
optimized vtklzma-9.0.lib
optimized vtkmetaio-9.0.lib
optimized vtknetcdf-9.0.lib
optimized vtkogg-9.0.lib
optimized vtkParallelCore-9.0.lib
optimized vtkParallelDIY-9.0.lib
optimized vtkpng-9.0.lib
optimized vtkpugixml-9.0.lib
optimized vtkRenderingAnnotation-9.0.lib
optimized vtkRenderingContext2D-9.0.lib
optimized vtkRenderingCore-9.0.lib
optimized vtkRenderingFreeType-9.0.lib
optimized vtkRenderingGL2PSOpenGL2-9.0.lib
optimized vtkRenderingImage-9.0.lib
optimized vtkRenderingLabel-9.0.lib
optimized vtkRenderingLOD-9.0.lib
optimized vtkRenderingOpenGL2-9.0.lib
optimized vtkRenderingQt-9.0.lib
optimized vtkRenderingSceneGraph-9.0.lib
optimized vtkRenderingUI-9.0.lib
optimized vtkRenderingVolume-9.0.lib
optimized vtkRenderingVolumeOpenGL2-9.0.lib
optimized vtkRenderingVtkJS-9.0.lib
optimized vtksqlite-9.0.lib
optimized vtksys-9.0.lib
optimized vtkTestingRendering-9.0.lib
optimized vtktheora-9.0.lib
optimized vtktiff-9.0.lib
optimized vtkverdict-9.0.lib
optimized vtkViewsContext2D-9.0.lib
optimized vtkViewsCore-9.0.lib
optimized vtkViewsInfovis-9.0.lib
optimized vtkViewsQt-9.0.lib
optimized vtkWrappingTools-9.0.lib
optimized vtkzlib-9.0.lib
)

set(VTK_LIB_Debug  
#debug QVTKWidgetPlugind.lib
debug vtkChartsCore-9.0d.lib
debug vtkCommonColor-9.0d.lib
debug vtkCommonComputationalGeometry-9.0d.lib
debug vtkCommonCore-9.0d.lib
debug vtkCommonDataModel-9.0d.lib
debug vtkCommonExecutionModel-9.0d.lib
debug vtkCommonMath-9.0d.lib
debug vtkCommonMisc-9.0d.lib
debug vtkCommonSystem-9.0d.lib
debug vtkCommonTransforms-9.0d.lib
debug vtkDICOMParser-9.0d.lib
debug vtkDomainsChemistry-9.0d.lib
debug vtkDomainsChemistryOpenGL2-9.0d.lib
debug vtkdoubleconversion-9.0d.lib
debug vtkexodusII-9.0d.lib
debug vtkexpat-9.0d.lib
debug vtkFiltersAMR-9.0d.lib
debug vtkFiltersCore-9.0d.lib
debug vtkFiltersExtraction-9.0d.lib
debug vtkFiltersFlowPaths-9.0d.lib
debug vtkFiltersGeneral-9.0d.lib
debug vtkFiltersGeneric-9.0d.lib
debug vtkFiltersGeometry-9.0d.lib
debug vtkFiltersHybrid-9.0d.lib
debug vtkFiltersHyperTree-9.0d.lib
debug vtkFiltersImaging-9.0d.lib
debug vtkFiltersModeling-9.0d.lib
debug vtkFiltersParallel-9.0d.lib
debug vtkFiltersParallelImaging-9.0d.lib
debug vtkFiltersPoints-9.0d.lib
debug vtkFiltersProgrammable-9.0d.lib
debug vtkFiltersSelection-9.0d.lib
debug vtkFiltersSMP-9.0d.lib
debug vtkFiltersSources-9.0d.lib
debug vtkFiltersStatistics-9.0d.lib
debug vtkFiltersTexture-9.0d.lib
debug vtkFiltersTopology-9.0d.lib
debug vtkFiltersVerdict-9.0d.lib
debug vtkfreetype-9.0d.lib
debug vtkGeovisCore-9.0d.lib
debug vtkgl2ps-9.0d.lib
debug vtkglew-9.0d.lib
debug vtkGUISupportQt-9.0d.lib
debug vtkGUISupportQtSQL-9.0d.lib
debug vtkhdf5-9.0d.lib
debug vtkhdf5_hl-9.0d.lib
debug vtkImagingColor-9.0d.lib
debug vtkImagingCore-9.0d.lib
debug vtkImagingFourier-9.0d.lib
debug vtkImagingGeneral-9.0d.lib
debug vtkImagingHybrid-9.0d.lib
debug vtkImagingMath-9.0d.lib
debug vtkImagingMorphological-9.0d.lib
debug vtkImagingSources-9.0d.lib
debug vtkImagingStatistics-9.0d.lib
debug vtkImagingStencil-9.0d.lib
debug vtkInfovisCore-9.0d.lib
debug vtkInfovisLayout-9.0d.lib
debug vtkInteractionImage-9.0d.lib
debug vtkInteractionStyle-9.0d.lib
debug vtkInteractionWidgets-9.0d.lib
debug vtkIOAMR-9.0d.lib
debug vtkIOAsynchronous-9.0d.lib
debug vtkIOCityGML-9.0d.lib
debug vtkIOCore-9.0d.lib
debug vtkIOEnSight-9.0d.lib
debug vtkIOExodus-9.0d.lib
debug vtkIOExport-9.0d.lib
debug vtkIOExportOpenGL2-9.0d.lib
debug vtkIOExportPDF-9.0d.lib
debug vtkIOGeometry-9.0d.lib
debug vtkIOImage-9.0d.lib
debug vtkIOImport-9.0d.lib
debug vtkIOInfovis-9.0d.lib
debug vtkIOLegacy-9.0d.lib
debug vtkIOLSDyna-9.0d.lib
debug vtkIOMINC-9.0d.lib
debug vtkIOMovie-9.0d.lib
debug vtkIONetCDF-9.0d.lib
debug vtkIOParallel-9.0d.lib
debug vtkIOParallelXML-9.0d.lib
debug vtkIOPLY-9.0d.lib
debug vtkIOSegY-9.0d.lib
debug vtkIOSQL-9.0d.lib
debug vtkIOTecplotTable-9.0d.lib
debug vtkIOVeraOut-9.0d.lib
debug vtkIOVideo-9.0d.lib
debug vtkIOXML-9.0d.lib
debug vtkIOXMLParser-9.0d.lib
debug vtkjpeg-9.0d.lib
debug vtkjsoncpp-9.0d.lib
debug vtklibharu-9.0d.lib
debug vtklibxml2-9.0d.lib
debug vtkLocalExample-9.0d.lib
debug vtklz4-9.0d.lib
debug vtklzma-9.0d.lib
debug vtkmetaio-9.0d.lib
debug vtkmyCommond.lib
debug vtkmyImagingd.lib
debug vtkmyUnsortedd.lib
debug vtkNetCDF-9.0d.lib
debug vtkogg-9.0d.lib
debug vtkParallelCore-9.0d.lib
debug vtkpng-9.0d.lib
debug vtkproj-9.0d.lib
debug vtkpugixml-9.0d.lib
debug vtkRenderingAnnotation-9.0d.lib
debug vtkRenderingContext2D-9.0d.lib
debug vtkRenderingContextOpenGL2-9.0d.lib
debug vtkRenderingCore-9.0d.lib
debug vtkRenderingFreeType-9.0d.lib
debug vtkRenderingGL2PSOpenGL2-9.0d.lib
debug vtkRenderingImage-9.0d.lib
debug vtkRenderingLabel-9.0d.lib
debug vtkRenderingLOD-9.0d.lib
debug vtkRenderingOpenGL2-9.0d.lib
debug vtkRenderingQt-9.0d.lib
debug vtkRenderingVolume-9.0d.lib
debug vtkRenderingVolumeOpenGL2-9.0d.lib
debug vtksqlite-9.0d.lib
debug vtksys-9.0d.lib
debug vtktheora-9.0d.lib
debug vtktiff-9.0d.lib
debug vtkverdict-9.0d.lib
debug vtkViewsContext2D-9.0d.lib
debug vtkViewsCore-9.0d.lib
debug vtkViewsInfovis-9.0d.lib
debug vtkViewsQt-9.0d.lib
debug vtkzlib-9.0d.lib
)